### ISSUE TITLE
Windows spawning in the workspace they were called from

### ISSUE THREAD

**Issue by brolaugh** [Vild/DWin#3]
In bspwm when you start e.g. Eclipse IDE in a workspace it will take ages to load and if you have switched workspace since you started Eclipse IDE and it has fully loaded a new window of Eclipse will spawn in the workspace you are currently working in. Instead of that happening the software being called should be bound to the workspace that it was started/called in if the user doesn't move it manually to another workspace.

**Comment by Vild** [comment]
Is already implemented.
Could be buggy, in that case open a new issue!
